### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by senator715** [nofanz/SunnyD#1]
Hello,

Please make an enhancement to this project by fixing the amount of copy paste that was added into the project.

I would love to see this used on my project again in the near future so I can laugh at its uselessness again.

Crack my cheat nerd

**Comment by cademtz** [comment]
What project and why do you want me to crack it?

**Comment by Aholicknight** [comment]
@senator715 post your cheat then

**Comment by senator715** [comment]
rijin.solutions, this time actually manage to open the dump in Ida this time instead of automatically getting raped by my system for your sunnyd dll before you even released this project
